version: '3.8'
services:
  flight-service:
    # TODO Add flight-service service configuration with the required environment variables (5 of them)
    # Port 8079 is exposed to the outside world
    # Don't forget to add the depends_on and networks configuration
    build:
      context: ./flight-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8079:8079"
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
      QUARKUS_DATASOURCE_REACTIVE_URL: vertx-reactive:postgresql://flight-db:5432/flight-database
      QUARKUS_GRPC_CLIENTS_PASSENGER_SERVICE_HOST: passenger-service
    depends_on:
      - flight-db
    networks:
      - app-network

  passenger-service:
    # TODO Add passenger-service service configuration with the required environment variables (5 of them)
    # Port 8078 and 9000 (grpc) are exposed to the outside world
    # Don't forget to add the depends_on and networks configuration
    build:
      context: ./passenger-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8078:8078"
      - "9000:9000"
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
      QUARKUS_DATASOURCE_REACTIVE_URL: vertx-reactive:postgresql://passenger-db:5432/passenger-database
#      It communicates on the internal port not exposed one
      QUARKUS_BAGGAGE_RESOURCE_URL: http://baggage-service:8077
    depends_on:
      - passenger-db
    networks:
      - app-network

  baggage-service:
    build:
      context: ./baggage-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8077:8077"
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
      QUARKUS_DATASOURCE_REACTIVE_URL: vertx-reactive:postgresql://baggage-db:5432/baggage-database
    depends_on:
      - baggage-db
    networks:
      - app-network

  flight-db:
    # TODO Add flight-db service configuration with the required environment variables (3 of them) and should match the flight-service configuration
    # Don't forget to add the volumes and networks configuration
    image: postgres:16.2
    environment:
      POSTGRES_DB: flight-database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - flight-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  passenger-db:
    # TODO Add passenger-db service configuration with the required environment variables (3 of them) and should match the passenger-service configuration
    # Don't forget to add the volumes and networks configuration
    image: postgres:16.2
    environment:
      POSTGRES_DB: passenger-database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - passenger-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  baggage-db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: baggage-database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - baggage-db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  # TODO add flight-db-data and passenger-db-data volumes
  flight-db-data:
  passenger-db-data:
  baggage-db-data:
